import type{EventRecord}from'../types';import{request}from'./api';
const common={status:'active',visibility:'unlisted',event_date:'2026-09-13',image_width:1280,image_height:720,video_width:1280,video_height:720,embedding_model:'DAKN-grid-gradient',embedding_version:'1.0.0',embedding_dimension:384,created_at:'2026-09-13T12:00:00.000Z',updated_at:'2026-09-13T12:00:00.000Z'}as const;
export const demoEvents:EventRecord[]=[
 {id:'00000000-0000-0000-0000-000000000101',slug:'cnep-uel-2026',title:'CNEP 2026 · UEL',partner_name:'Christina Noble Education Programme · UEL',description:'Những khoảnh khắc tại chương trình CNEP cùng Trường Đại học Kinh tế - Luật.',reference_image_path:'/data/CNEP-UEL/CNEP-UEL-Cover.jpg',thumbnail_path:'/data/CNEP-UEL/CNEP-UEL-Cover.jpg',video_path:'/data/CNEP-UEL/CNEP-UEL.mp4',video_duration:6.641,...common},
 {id:'00000000-0000-0000-0000-000000000102',slug:'cnep-ussh-2026',title:'CNEP 2026 · USSH',partner_name:'Christina Noble Education Programme · USSH',description:'Những khoảnh khắc tại chương trình CNEP cùng Trường Đại học Khoa học Xã hội và Nhân văn.',reference_image_path:'/data/CNEP-USSH/CNEP-USSH-Cover.jpg',thumbnail_path:'/data/CNEP-USSH/CNEP-USSH-Cover.jpg',video_path:'/data/CNEP-USSH/CNEP-USSH.mp4',video_duration:11.656,...common},
 {id:'00000000-0000-0000-0000-000000000103',slug:'cnep-yeah-2026',title:'CNEP 2026 · Yeah',partner_name:'Christina Noble Education Programme',description:'Những khoảnh khắc đáng nhớ của các bạn trẻ trong chương trình CNEP.',reference_image_path:'/data/CNEP-yeah/CNEP-yeah-Cover.jpg',thumbnail_path:'/data/CNEP-yeah/CNEP-yeah-Cover.jpg',video_path:'/data/CNEP-yeah/CNEP-yeah.mp4',video_duration:7.151,...common},
];
export const demoEvent=demoEvents[1];
function normalize(row:any):EventRecord{return{...row,reference_image_path:row.reference_image_path||row.reference_image_url,thumbnail_path:row.thumbnail_path||row.thumbnail_url||row.reference_image_url,video_path:row.video_path||row.video_url,target_path:row.target_path||row.target_url}}
export function assetUrl(path?:string){return path||''}
export async function publicEvent(slug:string){try{return normalize(await request(`/events/public/${slug}`))}catch(e){const demo=demoEvents.find(event=>event.slug===slug);if(demo)return demo;if((e as Error).message.includes('không tồn tại'))return null;throw e}}
export async function adminEvents(){try{return(await request<any[]>('/admin/events')).map(normalize)}catch{return demoEvents}}
export async function saveEvent(input:Partial<EventRecord>,files?:{image?:File;video?:File}){const form=new FormData();form.set('metadata',JSON.stringify(input));if(files?.image)form.set('image',files.image);if(files?.video)form.set('video',files.video);return normalize(await request('/admin/events',{method:'POST',body:form}))}
export async function setEventStatus(id:string,status:'active'|'inactive'){return normalize(await request(`/admin/events/${id}/status`,{method:'PATCH',body:JSON.stringify({status})}))}
