import'dotenv/config';import pg from'pg';import{v2 as cloudinary}from'cloudinary';import{spawnSync}from'node:child_process';
const assets=[
 {id:'00000000-0000-0000-0000-000000000101',slug:'cnep-uel-2026',title:'CNEP 2026 · UEL',partner:'Christina Noble Education Programme · UEL',description:'Những khoảnh khắc tại chương trình CNEP cùng Trường Đại học Kinh tế - Luật.',duration:6.641,image:'../Data/CNEP-UEL/CNEP-UEL-Cover.jpg',video:'../public/data/CNEP-UEL/CNEP-UEL.mp4'},
 {id:'00000000-0000-0000-0000-000000000102',slug:'cnep-ussh-2026',title:'CNEP 2026 · USSH',partner:'Christina Noble Education Programme · USSH',description:'Những khoảnh khắc tại chương trình CNEP cùng Trường Đại học Khoa học Xã hội và Nhân văn.',duration:11.656,image:'../Data/CNEP-USSH/CNEP-USSH-Cover.jpg',video:'../public/data/CNEP-USSH/CNEP-USSH.mp4'},
 {id:'00000000-0000-0000-0000-000000000103',slug:'cnep-yeah-2026',title:'CNEP 2026 · Yeah',partner:'Christina Noble Education Programme',description:'Những khoảnh khắc đáng nhớ của các bạn trẻ trong chương trình CNEP.',duration:7.151,image:'../Data/CNEP-yeah/CNEP-yeah-Cover.jpg',video:'../public/data/CNEP-yeah/CNEP-yeah.mp4'},
].map(item=>({...item,imagePath:decodeURIComponent(new URL(item.image,import.meta.url).pathname),videoPath:decodeURIComponent(new URL(item.video,import.meta.url).pathname)}));
cloudinary.config({cloud_name:process.env.CLOUDINARY_CLOUD_NAME,api_key:process.env.CLOUDINARY_API_KEY,api_secret:process.env.CLOUDINARY_API_SECRET});
function embedding(path){const result=spawnSync('ffmpeg',['-v','error','-i',path,'-vf','scale=224:224','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],{maxBuffer:224*224*3+1024});if(result.status!==0)throw new Error('Không đọc được ảnh seed');const d=result.stdout,v=[];for(let gy=0;gy<8;gy++)for(let gx=0;gx<8;gx++){let r=0,g=0,b=0,dx=0,dy=0,n=0;for(let y=gy*28;y<(gy+1)*28;y+=4)for(let x=gx*28;x<(gx+1)*28;x+=4){const i=(y*224+x)*3,j=(y*224+Math.min(223,x+1))*3,k=(Math.min(223,y+1)*224+x)*3;r+=d[i];g+=d[i+1];b+=d[i+2];dx+=Math.abs(d[i]-d[j]);dy+=Math.abs(d[i]-d[k]);n++}v.push(r/n/255,g/n/255,b/n/255,dx/n/255,dy/n/255,(Math.max(r,g,b)-Math.min(r,g,b))/n/255)}const norm=Math.hypot(...v)||1;return v.map(x=>x/norm)}
const pool=new pg.Pool({connectionString:process.env.DATABASE_URL}),owner='00000000-0000-0000-0000-000000000001',email=String(process.env.ADMIN_EMAIL||process.env.SUPER_ADMIN_EMAIL).toLowerCase();
await pool.query(`insert into dau_an_ket_noi.admins(id,email,password_hash) values($1,$2,'external-env') on conflict(email) do update set id=excluded.id`,[owner,email]);
for(const item of assets){const folder=`dau-an-ket-noi/demo/${item.slug}`,[image,video]=await Promise.all([cloudinary.uploader.upload(item.imagePath,{folder,public_id:'anh-dai-dien',overwrite:true,resource_type:'image'}),cloudinary.uploader.upload(item.videoPath,{folder,public_id:'video-ky-niem',overwrite:true,resource_type:'video'})]);await pool.query(`insert into dau_an_ket_noi.events(id,owner_id,slug,title,partner_name,event_date,description,status,visibility,reference_image_url,reference_image_public_id,thumbnail_url,video_url,video_public_id,image_width,image_height,video_duration,video_width,video_height,embedding,embedding_model,embedding_version,embedding_dimension) values($1,$2,$3,$4,$5,$6,$7,'active','unlisted',$8,$9,$8,$10,$11,1280,720,$12,1280,720,$13,'DAKN-grid-gradient','1.0.0',384) on conflict(id) do update set slug=excluded.slug,title=excluded.title,partner_name=excluded.partner_name,event_date=excluded.event_date,description=excluded.description,reference_image_url=excluded.reference_image_url,reference_image_public_id=excluded.reference_image_public_id,thumbnail_url=excluded.thumbnail_url,video_url=excluded.video_url,video_public_id=excluded.video_public_id,video_duration=excluded.video_duration,embedding=excluded.embedding,status='active',updated_at=now()`,[item.id,owner,item.slug,item.title,item.partner,'2026-09-13',item.description,image.secure_url,image.public_id,video.secure_url,video.public_id,item.duration,JSON.stringify(embedding(item.imagePath))]);console.log(`Seeded: ${item.title}`)}
await pool.end();
