import{FormEvent,useState}from'react';
import{Link,useNavigate}from'react-router-dom';
import{Brand,Status}from'../components/Brand';
import{quality,embed}from'../lib/cv';
import{saveEvent}from'../lib/events';
import{STORAGE,CV_CONFIG}from'../lib/config';
import type{QualityResult}from'../types';

export default function EventEditor({admin=false}:{admin?:boolean}){
 const[image,setImage]=useState<File>(),[video,setVideo]=useState<File>(),[q,setQ]=useState<QualityResult>(),[processing,setProcessing]=useState(false),[error,setError]=useState(''),nav=useNavigate(),base=admin?'/admin/events':'/account/events';
 async function chooseImage(f?:File){if(!f)return;if(!STORAGE.imageTypes.includes(f.type as any)||f.size>STORAGE.imageMax){setError('Ảnh không đúng định dạng hoặc vượt 12 MB.');return}setImage(f);setQ(await quality(f))}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!image||!video)return setError('Vui lòng chọn đủ ảnh và video.');setProcessing(true);setError('');try{const form=new FormData(e.currentTarget),bitmap=await createImageBitmap(image),url=URL.createObjectURL(image),vector=await embed(url);URL.revokeObjectURL(url);await saveEvent({slug:String(form.get('slug')),title:String(form.get('title')),partner_name:String(form.get('partner')),event_date:String(form.get('date')),description:String(form.get('description')),status:'ready',visibility:'unlisted',image_width:bitmap.width,image_height:bitmap.height,reference_image_path:'',thumbnail_path:'',video_path:'',embedding:vector,embedding_model:CV_CONFIG.model,embedding_version:CV_CONFIG.modelVersion,embedding_dimension:vector.length,created_at:new Date().toISOString(),updated_at:new Date().toISOString()},{image,video});nav(base)}catch(e:any){setError(e.message)}finally{setProcessing(false)}}
 return <main className="admin"><aside><Brand light/><nav><Link to={base}>← Các dấu ấn</Link></nav></aside><section className="admin-content editor"><header><div><p className="eyebrow">ĐĂNG KÝ NỘI DUNG</p><h1>Dấu ấn mới</h1></div></header><form onSubmit={submit}><fieldset><legend>01 · Thông tin sự kiện</legend><div className="form-grid"><label>Tên sự kiện<input name="title" required/></label><label>Đơn vị / đối tác<input name="partner" required/></label><label>Ngày diễn ra<input name="date" type="date" required/></label><label>Mã đường dẫn<input name="slug" required pattern="[a-z0-9-]+" placeholder="le-ky-ket-2026"/></label><label className="wide">Mô tả<textarea name="description" rows={3}/></label></div></fieldset><fieldset><legend>02 · Ảnh nhận diện</legend><label className="drop"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/><b>{image?.name||'Chọn hoặc thả ảnh vào đây'}</b><span>JPG, PNG, WebP · tối đa 12 MB</span></label>{q&&<div className="metrics"><span>Độ sáng <b>{q.brightness}/255</b></span><span>Tương phản <b>{q.contrast}</b></span><span>Độ nét <b>{q.sharpness}%</b></span><span>Đặc trưng <b>{q.keypoints}</b></span><Status value={q.verdict==='pass'?'ready':'failed'}/></div>}</fieldset><fieldset><legend>03 · Video sự kiện</legend><label className="drop"><input type="file" accept="video/mp4" onChange={e=>setVideo(e.target.files?.[0])}/><b>{video?.name||'Chọn video MP4'}</b><span>H.264 + AAC · khuyến nghị dưới 150 MB</span></label></fieldset>{error&&<p className="error">{error}</p>}<div className="savebar"><Link to={base} className="button secondary">Hủy</Link><button disabled={processing} className="button primary">{processing?'Đang tạo embedding…':'Xử lý & lưu dấu ấn'}</button></div></form></section></main>
}
