import{FormEvent,useEffect,useRef,useState}from'react';
import{useNavigate,Link,useSearchParams}from'react-router-dom';
import{Brand}from'../components/Brand';
import{request}from'../lib/api';
import{saveSession}from'../lib/auth';

type GoogleResponse={credential:string};
declare global{interface Window{google?:{accounts:{id:{initialize:(options:{client_id:string;callback:(response:GoogleResponse)=>void})=>void;renderButton:(element:HTMLElement,options:Record<string,unknown>)=>void}}}}}

type LoginResult={token:string;email?:string;role:'admin'|'user'};
export default function Login({admin=false}:{admin?:boolean}){
 const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[googleReady,setGoogleReady]=useState(false),googleButton=useRef<HTMLDivElement>(null),nav=useNavigate(),[params]=useSearchParams();
 function complete(data:LoginResult){if(admin&&data.role!=='admin'){setError('Tài khoản này không có quyền quản trị.');return}saveSession(data,email);const next=params.get('next'),safeNext=next?.startsWith('/')&&!next.startsWith('//')?next:null;nav(safeNext||(data.role==='admin'?'/admin/events':'/'))}
 async function googleLogin(response:GoogleResponse){setError('');try{complete(await request<LoginResult>('/auth/google',{method:'POST',body:JSON.stringify({credential:response.credential})}))}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(admin)return;let disposed=false;request<{enabled:boolean;clientId:string|null}>('/auth/google/config').then(config=>{if(disposed||!config.enabled||!config.clientId)return;setGoogleReady(true);const render=()=>{if(disposed||!googleButton.current||!window.google)return;window.google.accounts.id.initialize({client_id:config.clientId!,callback:googleLogin});const width=Math.max(240,Math.min(400,window.innerWidth-48));window.google.accounts.id.renderButton(googleButton.current,{type:'standard',theme:'outline',size:'large',text:'signin_with',shape:'pill',logo_alignment:'left',locale:'vi',width})},afterMount=()=>requestAnimationFrame(()=>requestAnimationFrame(render));if(window.google)return afterMount();const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=afterMount;script.onerror=()=>{setGoogleReady(false);setError('Không thể tải dịch vụ đăng nhập Google.')};document.head.appendChild(script)}).catch(()=>setGoogleReady(false));return()=>{disposed=true}},[admin]);
 async function submit(e:FormEvent){e.preventDefault();setError('');try{complete(await request<LoginResult>('/auth/login',{method:'POST',body:JSON.stringify({email,password})}))}catch(e:any){setError(e.message)}}
 return <main className="auth"><section className="auth-brand"><blockquote>“Mỗi cuộc gặp là một dấu ấn đáng trân trọng.”</blockquote></section><section className="auth-form"><header className="auth-topbar"><Brand/><Link to="/">← Trang công khai</Link></header><form onSubmit={submit}><p className="eyebrow">{admin?'KHU VỰC QUẢN TRỊ':'KHU VỰC TÀI KHOẢN'}</p><h1>{admin?'Đăng nhập quản trị':'Chào mừng trở lại'}</h1><p>{admin?'Chỉ tài khoản quản trị mới có thể truy cập khu vực này.':'Đăng nhập để mở camera và xem lại những dấu ấn.'}</p>{!admin&&(googleReady?<div className="google-signin" ref={googleButton}/>:<button type="button" className="google-fallback" onClick={()=>setError('Hãy khởi động API và kiểm tra GOOGLE_CLIENT_ID để đăng nhập Google.')}><b>G</b><span>Đăng nhập bằng Google</span></button>)}{!admin&&<div className="auth-divider"><span>hoặc đăng nhập bằng email</span></div>}<label>Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mật khẩu<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="button primary">Đăng nhập →</button>{admin?<p className="auth-switch">Tài khoản thường? <Link to="/login">Đăng nhập tại đây</Link></p>:<p className="auth-switch">Chưa có tài khoản? <Link to="/register">Đăng ký ngay</Link></p>}</form></section></main>
}
