import{ChangeEvent,useEffect,useRef,useState}from'react';
import{Link,useNavigate}from'react-router-dom';
import{CV_CONFIG}from'../lib/config';
import{demoEvent}from'../lib/events';
import{cosine,embed,loadEmbeddingModel}from'../lib/cv';
import{request}from'../lib/api';

type Stage='loading'|'scanning'|'checking'|'found'|'error';
type QRDetector={detect:(source:CanvasImageSource)=>Promise<Array<{rawValue:string}>>};

export default function Scan(){
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null),timer=useRef<number>(),busy=useRef(false),reference=useRef<number[]>(),qrDetector=useRef<QRDetector>();
 const[stage,setStage]=useState<Stage>('loading'),[message,setMessage]=useState('Đang mở camera…'),[progress,setProgress]=useState(0),[preview,setPreview]=useState('');const nav=useNavigate();
 const stop=()=>{clearInterval(timer.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null};
 useEffect(()=>{startCamera();return stop},[]);

 function openQR(text:string){try{const url=new URL(text,location.origin),match=url.pathname.match(/^\/e\/([a-z0-9-]+)(?:\/watch)?$/);if(!match)return false;stop();setStage('found');setMessage('Đã đọc mã QR');setTimeout(()=>nav(`/e/${match[1]}`),200);return true}catch{return false}}
 async function prepare(){setStage('loading');setMessage('Đang chuẩn bị nhận diện…');await loadEmbeddingModel(setProgress);reference.current??=await embed(demoEvent.reference_image_path);const Detector=(window as any).BarcodeDetector;if(Detector&&!qrDetector.current)try{qrDetector.current=new Detector({formats:['qr_code']})}catch{/* Trình duyệt không hỗ trợ QR native */}}
 async function checkCanvas(c:HTMLCanvasElement,finalAttempt=false){if(busy.current)return;busy.current=true;try{const codes=await qrDetector.current?.detect(c);if(codes?.[0]&&openQR(codes[0].rawValue))return;setStage('checking');setMessage('Đang tìm dấu ấn gần nhất…');const vector=await embed(c);let match:{slug:string;score:number}|undefined;try{match=(await request<{slug:string;score:number}[]>('/events/match',{method:'POST',body:JSON.stringify({embedding:vector,topK:1})}))[0]}catch{/* API ngoại tuyến: dùng seed cục bộ */}if(!match)match={slug:demoEvent.slug,score:cosine(vector,reference.current!)};if(match.score<CV_CONFIG.embeddingThreshold){if(finalAttempt){stop();nav('/e/khong-tim-thay?reason=no-match');return}setStage('scanning');setMessage('Đưa ảnh hoặc mã QR vào trong khung');return}stop();setStage('found');setMessage(`Đã khớp ${Math.round(match.score*100)}%`);setTimeout(()=>nav(`/e/${match.slug}?ar=1`),250)}catch(e:any){if(finalAttempt)nav('/e/khong-tim-thay?reason=processing-error');else{setStage('error');setMessage(e.message||'Không thể xử lý ảnh.')}}finally{busy.current=false}}
 async function startCamera(){try{stop();setPreview('');await prepare();stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280}},audio:false});if(!video.current)return;video.current.srcObject=stream.current;await video.current.play();setStage('scanning');setMessage('Đưa ảnh hoặc mã QR vào trong khung');timer.current=window.setInterval(()=>{if(!video.current?.videoWidth||busy.current)return;const c=captureFrame();if(c)checkCanvas(c)},CV_CONFIG.scanIntervalMs)}catch(e:any){stop();setStage('error');setMessage(e.name==='NotAllowedError'?'Bạn chưa cấp quyền camera. Hãy tải ảnh từ máy hoặc cấp lại quyền.':e.message||'Không thể mở camera.')}}
 function captureFrame(){if(!video.current?.videoWidth)return null;const c=document.createElement('canvas'),scale=Math.min(1,CV_CONFIG.maxFrameEdge/video.current.videoWidth);c.width=video.current.videoWidth*scale;c.height=video.current.videoHeight*scale;c.getContext('2d')!.drawImage(video.current,0,0,c.width,c.height);return c}
 async function takePhoto(){const c=captureFrame();if(!c)return;stop();setPreview(c.toDataURL('image/jpeg',.9));await checkCanvas(c,true)}
 async function uploadImage(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{stop();await prepare();const image=await createImageBitmap(file,{imageOrientation:'from-image'}),c=document.createElement('canvas'),scale=Math.min(1,CV_CONFIG.maxFrameEdge/image.width);c.width=image.width*scale;c.height=image.height*scale;c.getContext('2d')!.drawImage(image,0,0,c.width,c.height);setPreview(c.toDataURL('image/jpeg',.9));await checkCanvas(c,true)}catch{nav('/e/khong-tim-thay?reason=processing-error')}finally{e.target.value=''}}

 return <main className="scanner scanner-minimal"><video ref={video} muted playsInline/>{preview&&<img className="captured-preview" src={preview} alt="Ảnh đang được nhận diện"/>}<div className="scan-shade"/><Link to="/" onClick={stop} className="icon-btn close-button" aria-label="Đóng trình quét">✕</Link><div className="scan-frame"><i/><i/><i/><i/></div>{stage==='error'&&<div className="scan-error"><span>{message}</span><button onClick={startCamera}>Thử lại</button></div>}<div className="capture-actions"><button className="capture-button" onClick={takePhoto} disabled={!stream.current}>Chụp ảnh</button><label className="upload-only">Tải ảnh từ máy<input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadImage}/></label></div></main>
}
